blank_issues_enabled: false
contact_links:
    - name: Suncord Support Server
      url: https://discord.gg/VasF3Ma4Ab
      about: If you need help regarding Sunroof or Suncord, please join our support server!
